Skill.create(name: "パワーブレイク", effect: "敵の攻撃力を下げてダメージを与える", power: 40, job_id: 1)
Skill.create(name: "地烈拳", effect: "敵グループにダメージを与える", power: 35, job_id: 2)
Skill.create(name: "サンダー", effect: "敵グループに雷属性のダメージを与える", power: 60, job_id: 3)
Skill.create(name: "ケアル", effect: "味方を小回復", power: 40, job_id: 4)
Skill.create(name: "さみだれうち", effect: "敵に連続ダメージを与える", power: 20, job_id: 5)